version: "3"

services: # контейнеры Docker
  nginx:
    container_name: nginx
    build: requirements/nginx/ # сборка образа/путь до нашего nginx
    image: nginx
    restart: always
    ports: [443:443]
    volumes: [wp:/var/www/]
    depends_on: [wordpress] # зависимость - ждет пока не подгрузятся прописанные сервисы (wordpress)
    networks: [inception]

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    image: wordpress
    restart: always
    networks: [inception]
    env_file: .env
    volumes: [wp:/var/www/]
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    image: mariadb
    restart: always # restart_policy - более глубокие настройки перезагрузки
    volumes: [db:/var/lib/mysql]
    networks: [inception]
    env_file: .env
    healthcheck:
      test: ['CMD', 'mariadb', '-p$DB_PASSWORD']
      interval: 7s
      retries: 5
      start_period: 10s

  # bonus
  redis:
    build: requirements/bonus/redis/
    container_name: redis
    image: redis
    restart: always
    networks: [inception]
    ports: [6379:6379]
    env_file: .env
    depends_on: [wordpress]
  
  adminer:
    build: requirements/bonus/adminer/ 
    container_name: adminer
    image: adminer
    depends_on: [wordpress]
    volumes: [wp:/var/www/]
    networks: [inception]

  my_site:
    build: requirements/bonus/my_site/
    container_name: my_site
    image: my_site
    env_file: .env
    networks: [inception]
    volumes: [wp:/var/www/]
    depends_on: [nginx]

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind # двойная связь, сохраняет файлы в на локальную машину и контейнер
      device: /home/dlana/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dlana/data/wp

networks: 
  inception:
    name: inception
    driver: bridge
