version: "3"

services: # контейнеры Docker
  nginx:
    container_name: nginx
    build: requirements/nginx/ # сборка образа/путь до нашего nginx
    restart: always
    ports: [443:443]
    volumes: [wp:/var/www/]
    depends_on: [wordpress] # зависимость - ждет пока не подгрузятся прописанные сервисы (wordpress)
    networks: [default]

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    restart: always
    networks: [default]
    env_file: .env
    volumes: [wp:/var/www/]
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always # restart_policy - более глубокие настройки перезагрузки
    volumes: [db:/var/lib/mysql]
    networks: [default]
    env_file: .env
    healthcheck:
      test: ['CMD', 'mariadb', '-p$DB_PASSWORD']
      interval: 5s
      retries: 5
      start_period: 10s

  #bonus
  redis:
    build: requirements/bonus/redis/
    container_name: redis
    restart: always
    networks: [default]
    ports: [6379:6379]
    env_file: .env
    depends_on: [wordpress]
  
  adminer:
    build: requirements/bonus/adminer/ 
    container_name: adminer
    depends_on: [wordpress]
    volumes: [wp:/var/www/]
    networks: [default]

  python:
    build: requirements/bonus/python-app/
    container_name: python
    restart: always
    env_file: .env
    networks: [default]

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind # двойная связь, сохраняет файлы в на локальную машину и контейнер
      device: /home/dlana/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dlana/data/wp

networks: 
  default:
    driver: bridge
